#!/usr/bin/env node
// generate.mjs — LLM study-material generator for exam-tutor.html
//
// Default provider is the DeepSeek direct API; OpenRouter is kept as a fallback
// selected with --provider openrouter.
//
// Usage:
//   node scripts/generate.mjs --subject ss --topic "Mughal Empire" --n 5
//   node scripts/generate.mjs --subject sms --topic "Number Systems" --n 6 --day 27
//   node scripts/generate.mjs --subject lang-hi --topic "हिन्दी व्याकरण" --n 5
//   node scripts/generate.mjs --subject reason --topic "Analogy" --provider openrouter
//   node scripts/generate.mjs --manifest            # batch: fill every uncovered topic
//   node scripts/generate.mjs --manifest --dry-run  # preview the batch without writing
//   node scripts/generate.mjs --daily               # daily: Current Affairs + GK/GS + section rotation
//
// Output is APPENDED (never overwritten) to content/generated/<subject>.js and
// logged to content/generated/manifest.json so no generated info is ever lost.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { PROMPTS } from "./prompts.mjs";
import { validateModule, validateQuestion, qHash } from "./validate.mjs";
import { TOPICS } from "./topics.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content", "generated");

const DATA_START = "/*__DATA_START__*/";
const DATA_END = "/*__DATA_END__*/";

/* ---------- args ---------- */
function parseArgs(argv) {
  const a = { n: 5 };
  for (let i = 0; i < argv.length; i++) {
    const k = argv[i];
    const v = argv[i + 1];
    if (k === "--subject") a.subject = v, i++;
    else if (k === "--topic") a.topic = v, i++;
    else if (k === "--branch") a.branch = v, i++;
    else if (k === "--n") a.n = parseInt(v, 10), i++;
    else if (k === "--model") a.model = v, i++;
    else if (k === "--day") a.day = parseInt(v, 10), i++;
    else if (k === "--provider") a.provider = v, i++;
    else if (k === "--delay") a.delay = parseInt(v, 10), i++;
    else if (k === "--manifest" || k === "--all") a.manifest = true;
    else if (k === "--daily") a.daily = true;
    else if (k === "--dry-run") a.dryRun = true;
    else if (k === "--help") a.help = true;
  }
  return a;
}

/* ---------- env ---------- */
function loadEnv() {
  const envPath = path.join(ROOT, ".env");
  const env = { ...process.env };
  if (!existsSync(envPath)) return env;
  const txt = readFileSync(envPath, "utf8");
  for (const line of txt.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return env;
}

/* ---------- helpers ---------- */
function slug(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9\u0900-\u097F]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "topic";
}
function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}
function readGenerated(subject) {
  const file = path.join(CONTENT_DIR, subject + ".js");
  if (!existsSync(file)) return [];
  const txt = readFileSync(file, "utf8");
  const s = txt.indexOf(DATA_START);
  const e = txt.indexOf(DATA_END);
  if (s === -1 || e === -1) return [];
  const raw = txt.slice(s + DATA_START.length, e).trim();
  if (!raw) return [];
  try { return JSON.parse(raw); } catch { return []; }
}
function writeGenerated(subject, modules) {
  const file = path.join(CONTENT_DIR, subject + ".js");
  mkdirSync(CONTENT_DIR, { recursive: true });
  const header = "// AUTO-GENERATED by scripts/generate.mjs — appended, never overwritten. Do not edit by hand.\n" +
    "window.GENERATED_MODULES = window.GENERATED_MODULES || [];\n" +
    `window.GENERATED_MODULES.push(...${DATA_START}${JSON.stringify(modules)}${DATA_END});\n`;
  writeFileSync(file, header, "utf8");
  return file;
}
function appendManifest(rec) {
  const file = path.join(CONTENT_DIR, "manifest.json");
  const existing = existsSync(file) ? JSON.parse(readFileSync(file, "utf8") || "[]") : [];
  existing.push(rec);
  writeFileSync(file, JSON.stringify(existing, null, 2) + "\n", "utf8");
}

/* ---------- LLM providers ---------- */
async function callLLM(env, model, messages) {
  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": "Bearer " + env.OPENROUTER_API_KEY,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ model, messages, temperature: 0.5, response_format: { type: "json_object" } }),
  });
  if (!res.ok) throw new Error("OpenRouter HTTP " + res.status + ": " + (await res.text()).slice(0, 400));
  const data = await res.json();
  return data.choices?.[0]?.message?.content || "";
}

async function callDeepSeek(env, model, messages) {
  const res = await fetch("https://api.deepseek.com/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": "Bearer " + env.DEEPSEEK_API_KEY,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ model: model || "deepseek-chat", messages, temperature: 0.5, response_format: { type: "json_object" } }),
  });
  if (!res.ok) throw new Error("DeepSeek HTTP " + res.status + ": " + (await res.text()).slice(0, 400));
  const data = await res.json();
  return data.choices?.[0]?.message?.content || "";
}

function resolveProvider(a, env) {
  const p = String(a.provider || "deepseek").toLowerCase();
  if (p === "deepseek") {
    if (!env.DEEPSEEK_API_KEY) {
      throw new Error("Missing DEEPSEEK_API_KEY (--provider deepseek is the default). Add it to .env or pass --provider openrouter.");
    }
    const model = a.model || "deepseek-chat";
    return { name: "deepseek", model, call: (m) => callDeepSeek(env, model, m) };
  }
  if (p === "openrouter") {
    if (!env.OPENROUTER_API_KEY) {
      throw new Error("Missing OPENROUTER_API_KEY for --provider openrouter. Add it to .env or pass --provider deepseek.");
    }
    const model = a.model || env.OPENROUTER_MODEL || "deepseek/deepseek-chat";
    return { name: "openrouter", model, call: (m) => callLLM(env, model, m) };
  }
  throw new Error("Unknown --provider '" + a.provider + "' (use deepseek or openrouter).");
}

function extractJSON(text) {
  const t = text.trim().replace(/^```(?:json)?/i, "").replace(/```$/g, "").trim();
  try { return JSON.parse(t); } catch {}
  const a = t.indexOf("{"), b = t.lastIndexOf("}");
  if (a !== -1 && b > a) { try { return JSON.parse(t.slice(a, b + 1)); } catch {} }
  throw new Error("Could not parse JSON from LLM response");
}

/* ---------- generate one topic (append, dedupe) ---------- */
async function generateOne(env, o) {
  const prov = resolveProvider(o, env);
  const n = Math.max(1, Math.min(20, o.n || 5));

  // Idempotency: one generated module per roadmap day. Skip before spending an
  // API call if this day already has a generated module (prevents duplicates when
  // a run is retried or a previous attempt partially succeeded).
  const existing = readGenerated(o.subject);
  if (o.day > 0 && existing.some((m) => m.day === o.day)) {
    return { added: 0, skipped: 0, duplicate: true, alreadyByDay: true };
  }

  const messages = [
    { role: "system", content: PROMPTS.system },
    { role: "user", content: PROMPTS.user(o.subject, o.topic, o.branch, n) },
  ];

  let parsed;
  try {
    parsed = extractJSON(await prov.call(messages));
  } catch (e) {
    messages.push({ role: "assistant", content: "I got an error: " + e.message });
    messages.push({ role: "user", content: "Your previous JSON was invalid. Return ONLY valid JSON matching the required schema." });
    parsed = extractJSON(await prov.call(messages));
  }

  const id = `gen-${o.subject}-${slug(o.topic)}-${Date.now().toString(36)}`;
  const concept = parsed.concept || {};
  const moduleObj = {
    id,
    subject: o.subject,
    day: o.day || 0,
    level: 1,
    title: parsed.title || o.topic,
    hi: parsed.title_hi || o.topic,
    concepts: [{
      title: concept.title || parsed.title || o.topic,
      title_hi: concept.title_hi || parsed.title_hi || o.topic,
      simple: concept.simple || "",
      simple_hi: concept.simple_hi || "",
      intro: "",
      points: Array.isArray(concept.points) ? concept.points : [],
      example: concept.example || "",
      trick: concept.trick || "",
      deep: {
        title: "Deep Dive",
        title_hi: "गहन अध्ययन",
        body: concept.deep || "Advanced context for this topic.",
        body_hi: concept.deep_hi || concept.deep || "इस विषय का उन्नत संदर्भ।",
      },
    }],
    questions: Array.isArray(parsed.questions) ? parsed.questions : [],
  };

  const errs = validateModule(moduleObj, o.subject + ": ");
  if (errs.length) {
    throw new Error("Validation failed: " + errs.join("; "));
  }

  const seen = new Set();
  existing.forEach((m) => (m.questions || []).forEach((q) => seen.add(qHash(q))));
  const newQ = moduleObj.questions.filter((q) => !seen.has(qHash(q)));
  const added = newQ.length;
  const skipped = moduleObj.questions.length - added;

  if (!added) return { added: 0, skipped, duplicate: true };

  moduleObj.questions = newQ;
  const merged = existing.concat([moduleObj]);
  if (o.dryRun) {
    return { added, skipped, dryRun: true, moduleObj };
  }
  const file = writeGenerated(o.subject, merged);
  try {
    appendManifest({
      ts: new Date().toISOString(),
      subject: o.subject,
      topic: o.topic,
      branch: o.branch || null,
      model: prov.model,
      provider: prov.name,
      day: o.day || null,
      moduleId: id,
      requested: n,
      added,
      skipped,
    });
  } catch { /* log-only failure must not undo a successful write */ }
  return { added, skipped, file: path.relative(ROOT, file) };
}

/* ---------- batch mode (--manifest / --all) ---------- */
function alreadyGenerated(cached, t) {
  return cached.some((m) =>
    (t.day > 0 && m.day === t.day) ||
    m.title === t.topic ||
    m.hi === t.topic_hi
  );
}

async function runManifest(env, o) {
  resolveProvider(o, env); // fail fast if the selected provider key is missing
  const targets = TOPICS.filter((t) => !t.covered);
  const delayMs = Math.max(0, o.delay || 800);
  const cache = {};
  const summary = { generated: 0, skippedExisting: 0, failed: 0 };

  console.log(`→ Batch manifest: ${targets.length} uncovered topics · provider=${o.provider || "deepseek"} · n=${o.n || 5}${o.dryRun ? " · DRY-RUN" : ""}`);

  for (let i = 0; i < targets.length; i++) {
    const t = targets[i];
    const cached = cache[t.subject] ?? (cache[t.subject] = readGenerated(t.subject));
    if (alreadyGenerated(cached, t)) { summary.skippedExisting++; continue; }

    const label = `[${i + 1}/${targets.length}] ${t.subject}/${t.topic}`;
    process.stdout.write(label + " … ");
    try {
      const res = await generateOne(env, { subject: t.subject, topic: t.topic, branch: null, n: o.n || 5, day: t.day, model: o.model, provider: o.provider, dryRun: o.dryRun });
      if (res.duplicate) { summary.skippedExisting++; console.log("duplicates skipped"); }
      else if (res.dryRun) { summary.generated++; console.log(`DRY-RUN ${res.added} questions`); }
      else { summary.generated++; console.log(`✓ ${res.added} questions → ${res.file}`); }
    } catch (e) {
      await sleep(delayMs);
      try {
        const res = await generateOne(env, { subject: t.subject, topic: t.topic, branch: null, n: o.n || 5, day: t.day, model: o.model, provider: o.provider, dryRun: o.dryRun });
        if (res.duplicate) { summary.skippedExisting++; console.log("duplicates skipped (retry)"); }
        else if (res.dryRun) { summary.generated++; console.log(`DRY-RUN (retry) ${res.added} questions`); }
        else { summary.generated++; console.log(`✓ (retry) ${res.added} questions`); }
      } catch (e2) {
        summary.failed++;
        console.log("✗ " + e2.message);
      }
    }
    await sleep(delayMs);
  }

  console.log(`\nSummary: ${summary.generated} generated, ${summary.skippedExisting} already present, ${summary.failed} failed.`);
}

/* ---------- daily mode (--daily) ---------- */
// GK/GS rotation pool — two of these are refreshed every day (day 0 = subject pool).
const DAILY_GK_GS = [
  ["gk", "General Science — Physics, Chemistry, Biology"],
  ["gk", "Environment, Ecology & Climate"],
  ["gk", "Science & Technology — Space, Defence, IT"],
  ["gk", "Sports, Awards & Honours"],
  ["gk", "Books & Authors"],
  ["gk", "World Geography & Continents"],
  ["gk", "Indian Economy — Budget, RBI & Banking"],
  ["gk", "Indian Constitution — Articles & Amendments"],
  ["gk", "Indian Polity & Governance"],
  ["gk", "Indian Geography"],
  ["gk", "Indian History & National Movement"],
  ["sms", "Science: Daily-life Science, Inventions & Technology"],
];

// Section rotation — one extra section gets new practice questions every day.
const DAILY_SECTIONS = ["reason", "ss", "sms", "lang-hi", "lang-en", "lang-sa"];

function dayOfYear() {
  const d = new Date();
  return Math.floor((d - new Date(d.getFullYear(), 0, 0)) / 864e5);
}
const normTitle = (s) => String(s || "").toLowerCase().replace(/\s+/g, " ").trim();

// Append new practice questions to an existing generated module, or create the
// module (with concept) when it does not exist yet.
async function topUpTopic(env, o) {
  const prov = resolveProvider(o, env);
  const n = Math.max(1, Math.min(20, o.n || 6));
  const existing = readGenerated(o.subject);

  const match = o.fresh ? null : existing.find((m) =>
    normTitle(m.title) === normTitle(o.topic) ||
    (o.topic_hi && normTitle(m.hi) === normTitle(o.topic_hi)) ||
    (o.day > 0 && m.day === o.day)
  );

  if (!match) return generateOne(env, o);

  const messages = [
    { role: "system", content: PROMPTS.system },
    { role: "user", content: PROMPTS.moreQuestions(o.subject, o.topic, n) },
  ];
  let parsed;
  try {
    parsed = extractJSON(await prov.call(messages));
  } catch (e) {
    messages.push({ role: "assistant", content: "I got an error: " + e.message });
    messages.push({ role: "user", content: "Your previous JSON was invalid. Return ONLY valid JSON matching the required schema." });
    parsed = extractJSON(await prov.call(messages));
  }

  const qs = Array.isArray(parsed.questions) ? parsed.questions : [];
  const errs = [];
  qs.forEach((q, i) => errs.push(...validateQuestion(q, o.subject + " q" + i + ": ")));
  if (errs.length) throw new Error("Validation failed: " + errs.join("; "));
  if (!qs.length) return { toppedUp: 0, skipped: 0, duplicate: true };

  const seen = new Set((match.questions || []).map(qHash));
  const newQ = qs.filter((q) => !seen.has(qHash(q)));
  const added = newQ.length;
  const skipped = qs.length - added;
  if (!added) return { toppedUp: 0, skipped, duplicate: true };

  match.questions = (match.questions || []).concat(newQ);
  const file = writeGenerated(o.subject, existing);
  try {
    appendManifest({
      ts: new Date().toISOString(),
      subject: o.subject,
      topic: o.topic,
      branch: null,
      model: prov.model,
      provider: prov.name,
      day: match.day || null,
      moduleId: match.id,
      requested: n,
      added,
      skipped,
      mode: "topup",
    });
  } catch { /* log-only failure must not undo a successful write */ }
  return { toppedUp: added, skipped, file: path.relative(ROOT, file) };
}

async function runDaily(env, o) {
  resolveProvider(o, env); // fail fast if the selected provider key is missing
  const n = Math.max(1, Math.min(20, o.n || 6));
  const delayMs = Math.max(0, o.delay || 800);
  const today = new Date().toISOString().slice(0, 10);
  const doy = dayOfYear();

  const tasks = [];
  // 1) Fresh Current Affairs module every day (dated title, always new).
  tasks.push({ subject: "gk", topic: `Current Affairs — ${today}`, day: 0, n, fresh: true });
  // 2) Two GK/GS topics from the rotation pool.
  const t1 = DAILY_GK_GS[doy % DAILY_GK_GS.length];
  const t2 = DAILY_GK_GS[(doy + Math.floor(DAILY_GK_GS.length / 2)) % DAILY_GK_GS.length];
  for (const [subject, topic] of [t1, t2]) {
    if (!tasks.some((t) => t.subject === subject && t.topic === topic)) {
      tasks.push({ subject, topic, day: 0, n });
    }
  }
  // 3) Section rotation — new quizzes for one more section every day.
  const subj = DAILY_SECTIONS[doy % DAILY_SECTIONS.length];
  const candidates = TOPICS.filter((t) => t.subject === subj);
  const uncovered = candidates.filter((t) => !t.covered);
  const pool = uncovered.length ? uncovered : candidates;
  const pick = pool[doy % pool.length];
  tasks.push({ subject: subj, topic: pick.topic, topic_hi: pick.topic_hi, day: pick.covered ? 0 : (pick.day || 0), n });

  console.log(`→ Daily content update · ${today} · provider=${o.provider || "deepseek"} · n=${n}${o.dryRun ? " · DRY-RUN" : ""}`);
  if (o.dryRun) {
    tasks.forEach((t, i) => console.log(`  [${i + 1}/${tasks.length}] ${t.subject}/${t.topic}${t.day ? ` (day ${t.day})` : ""}${t.fresh ? " · fresh" : ""}`));
    console.log("\nDRY-RUN: no API calls were made.");
    return;
  }

  const summary = { generated: 0, toppedUp: 0, skipped: 0, failed: 0 };
  for (let i = 0; i < tasks.length; i++) {
    const t = tasks[i];
    process.stdout.write(`[${i + 1}/${tasks.length}] ${t.subject}/${t.topic} … `);
    try {
      const res = await topUpTopic(env, t);
      if (res.duplicate) { summary.skipped++; console.log("no new questions (all duplicates)"); }
      else if (res.toppedUp != null) { summary.toppedUp += res.toppedUp; console.log(`✓ +${res.toppedUp} questions → ${res.file}`); }
      else { summary.generated++; console.log(`✓ new module, ${res.added} questions → ${res.file}`); }
    } catch (e) {
      await sleep(delayMs);
      try {
        const res = await topUpTopic(env, t);
        if (res.duplicate) { summary.skipped++; console.log("no new questions (all duplicates, retry)"); }
        else if (res.toppedUp != null) { summary.toppedUp += res.toppedUp; console.log(`✓ (retry) +${res.toppedUp} questions`); }
        else { summary.generated++; console.log(`✓ (retry) new module, ${res.added} questions`); }
      } catch (e2) {
        summary.failed++;
        console.log("✗ " + e2.message);
      }
    }
    await sleep(delayMs);
  }
  console.log(`\nSummary: ${summary.generated} new modules, +${summary.toppedUp} questions appended, ${summary.skipped} skipped, ${summary.failed} failed.`);
}

/* ---------- main ---------- */
function usage() {
  console.log("Usage:");
  console.log("  node scripts/generate.mjs --subject <id> --topic \"<name>\" [--provider deepseek|openrouter] [--branch hi|en|sa] [--n 5] [--day N] [--model <id>] [--dry-run]");
  console.log("  node scripts/generate.mjs --manifest [--provider deepseek|openrouter] [--n 5] [--dry-run]");
  console.log("  node scripts/generate.mjs --daily [--provider deepseek|openrouter] [--n 6] [--dry-run]");
  console.log("Subjects: gk, reason, ss, sms, lang-hi, lang-en, lang-sa");
  console.log("Providers: deepseek (default, direct API), openrouter (fallback).");
  console.log("--daily: fresh Current Affairs + 2 rotating GK/GS topics + 1 rotating section, every day.");
}

async function main() {
  const a = parseArgs(process.argv.slice(2));
  if (a.help) { usage(); process.exit(0); }

  if (a.daily) {
    await runDaily(loadEnv(), a);
    return;
  }

  if (a.manifest) {
    await runManifest(loadEnv(), a);
    return;
  }

  if (!a.subject || !a.topic) { usage(); process.exit(1); }

  const env = loadEnv();
  const prov = resolveProvider(a, env);
  const n = Math.max(1, Math.min(20, a.n));
  console.log(`→ Generating ${n} MCQs · subject=${a.subject} · topic="${a.topic}" · provider=${prov.name} · model=${prov.model}`);

  const res = await generateOne(env, a);
  if (res.duplicate) {
    console.log("ℹ All generated questions were duplicates of existing content — nothing appended (no data lost).");
  } else if (res.dryRun) {
    console.log(`DRY-RUN (no write): would append ${res.added} questions, ${res.skipped} skipped (duplicates).`);
    console.log(JSON.stringify(res.moduleObj, null, 2).slice(0, 1500));
  } else {
    console.log(`✓ Appended ${res.added} questions (${res.skipped} duplicate skipped) → ${res.file}`);
  }
}

export {
  parseArgs, loadEnv, readGenerated, writeGenerated, appendManifest,
  extractJSON, callLLM, callDeepSeek, resolveProvider, generateOne, runManifest,
  topUpTopic, runDaily, DAILY_GK_GS, DAILY_SECTIONS,
};

const isDirect = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isDirect) main().catch((e) => { console.error("✗ " + e.message); process.exit(1); });
